version: "3"
services:
  webspl:
    image: joszamama/webspl
    container_name: webspl
    restart: unless-stopped
    stdin_open: true 
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - mysql
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'webspl'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: